# Generated by Django 5.2.14 on 2026-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0003_task_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
