# Generated by Django 5.2.14 on 2026-05-18 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0004_alter_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("dob", models.DateField()),
            ],
            options={
                "ordering": ["lastname", "firstname"],
            },
        ),
    ]
