# Generated by Django 5.2.14 on 2026-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0005_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
